// AUTO-GENERATED by scripts/build-kb.mjs from docs/help/*.md. Do not edit by hand.
import type { Article } from "./kb";

export const ARTICLES: Article[] = [
  {
    "id": "getting-started",
    "title": "Signing in and getting started",
    "tags": [
      "login",
      "sign in",
      "account",
      "start",
      "first time"
    ],
    "body": "ChillMind opens on the sign-in screen. Enter your name to start a session, and you go straight to your dashboard.\n\nThe first time you sign in, ChillMind runs a short wellness survey so it can tailor your dashboard. You can skip it and take it later from your profile.\n\nYour session lasts as long as the app is open. Refreshing the page starts a new session, so finish anything in progress before you reload."
  },
  {
    "id": "breathing",
    "title": "Breathing exercises",
    "tags": [
      "breathing",
      "breathe",
      "exercise",
      "calm",
      "session",
      "box breathing"
    ],
    "body": "Open **Breathing** from the sidebar to run a guided breathing session.\n\nPick a pattern, press start, and follow the on-screen animation — inhale as it grows, exhale as it shrinks. A session takes a couple of minutes.\n\nEach completed session is added to your breathing history and counts towards your breathing streak. If you stop partway through, the session is not counted."
  },
  {
    "id": "breathing-streaks",
    "title": "Breathing streaks and history",
    "tags": [
      "streak",
      "history",
      "reset",
      "days",
      "consecutive"
    ],
    "body": "Your breathing streak counts consecutive days with at least one completed breathing session. Miss a day and the streak returns to zero on your next session.\n\nYour breathing history is shown on the Breathing page and summarised on your profile.\n\nThere is no manual reset button for a streak. Because ChillMind keeps your progress for the current session only, refreshing the page clears your streak and history along with the rest of your session data."
  },
  {
    "id": "focus-drills",
    "title": "Focus drills and scores",
    "tags": [
      "focus",
      "drill",
      "score",
      "level",
      "concentration",
      "number"
    ],
    "body": "The focus drill shows a number for a moment, hides it, and asks you to type it back. Each correct answer raises your level and your streak; a wrong answer resets the streak.\n\nYour focus score, high score, level, and accuracy are tracked as you play, and accuracy is calculated from your total correct answers against total attempts.\n\nDrills get harder as your level rises by showing longer numbers for less time."
  },
  {
    "id": "word-jumble",
    "title": "Word jumble",
    "tags": [
      "jumble",
      "word",
      "anagram",
      "hint",
      "puzzle"
    ],
    "body": "Word jumble scrambles a word and asks you to unscramble it. Solve it to raise your score and streak, then move to the next word.\n\nIf you are stuck, ask for a hint — ChillMind gives you a clue about the word rather than the answer itself.\n\nLevels increase as you solve more words, and longer words appear at higher levels."
  },
  {
    "id": "memory-game",
    "title": "Memory game",
    "tags": [
      "memory",
      "cards",
      "match",
      "pairs",
      "moves"
    ],
    "body": "The memory game lays out face-down cards. Tap two to reveal them; matching cards stay up and non-matching cards flip back.\n\nYour moves are counted as you play, and clearing the board with fewer moves scores higher. Levels add more pairs."
  },
  {
    "id": "daily-goals",
    "title": "Daily goals",
    "tags": [
      "goals",
      "daily",
      "tasks",
      "checklist",
      "todo"
    ],
    "body": "Daily goals live on your main dashboard. Add a goal, then tick it off when it's done.\n\nCompleted goals feed the progress shown on your dashboard and profile. Goals are for the current day, and they are part of your session data, so they clear when the session ends."
  },
  {
    "id": "calendar",
    "title": "Calendar and schedule",
    "tags": [
      "calendar",
      "schedule",
      "event",
      "date",
      "month",
      "plan"
    ],
    "body": "Open **Calendar** from the sidebar to see your month. Select any date to see what you have scheduled.\n\nTo add something, choose the date, then add a schedule item with a time, an activity name, and an icon. Items appear under the date you selected.\n\nYou can switch between month and day views from the controls at the top of the Calendar page."
  },
  {
    "id": "notifications",
    "title": "Notifications",
    "tags": [
      "notification",
      "alert",
      "unread",
      "reminder",
      "missed",
      "upcoming"
    ],
    "body": "The **Notifications** page lists reminders ChillMind has raised — upcoming scheduled items and tasks you have missed.\n\nYou can mark a single notification as read, mark everything as read at once, delete one notification, or clear the whole list. The sidebar shows a count of unread notifications.\n\nThe list is paginated. Use the page controls at the bottom to move between pages, and change how many notifications appear per page."
  },
  {
    "id": "notification-preferences",
    "title": "Turning notifications on and off",
    "tags": [
      "notification",
      "preferences",
      "settings",
      "mute",
      "turn off"
    ],
    "body": "Notification preferences are on the Notifications page. Turn individual notification types on or off there — for example upcoming reminders separately from missed-task alerts.\n\nTurning a type off stops new notifications of that type. It does not delete notifications you have already received; clear those from the list itself."
  },
  {
    "id": "profile",
    "title": "Your profile and stats",
    "tags": [
      "profile",
      "stats",
      "progress",
      "summary",
      "account"
    ],
    "body": "Your profile brings together your progress: breathing sessions and streak, focus and game scores, accuracy, and how far you have got with your daily goals.\n\nYou can retake the wellness survey from your profile if you want your dashboard to reflect how you are doing now."
  },
  {
    "id": "mentor-chat",
    "title": "The AI Mentor chat",
    "tags": [
      "mentor",
      "chat",
      "ai",
      "talk",
      "advice",
      "assistant"
    ],
    "body": "The Mentor is the chat on your dashboard. Ask about study techniques, focus, motivation, stress, or mindfulness and it replies in the conversation.\n\nThe Mentor keeps the recent part of your conversation in mind, so you can ask follow-up questions without repeating yourself.\n\nThe Mentor is a supportive study companion, not a counsellor or a doctor. It does not diagnose anything and does not give medical or medication advice."
  },
  {
    "id": "privacy",
    "title": "Your data and privacy",
    "tags": [
      "privacy",
      "data",
      "delete",
      "stored",
      "personal",
      "security"
    ],
    "body": "ChillMind keeps your wellbeing data — breathing history, scores, goals, schedule items, and chat — for the current session only. Nothing is written to a permanent database, and refreshing the page clears it.\n\nBecause nothing is stored permanently, there is no separate delete-my-data step: ending your session removes it.\n\nYour conversation with the Mentor is not shared with other users."
  },
  {
    "id": "troubleshooting",
    "title": "When something looks wrong",
    "tags": [
      "broken",
      "error",
      "missing",
      "lost",
      "blank",
      "slow",
      "bug"
    ],
    "body": "If your progress has vanished, the most likely cause is a page refresh or a new session, which clears session data by design.\n\nIf a page looks blank or a control does not respond, reload the app to start a clean session.\n\nIf the Mentor replies with a short generic message, its AI service was briefly unavailable and it fell back to built-in replies. Try again in a moment."
  }
];
