/**
 * Generates web/lib/kb-data.ts from docs/help/*.md.
 *
 * The corpus is compiled in rather than read from disk at runtime so it works
 * unchanged on Vercel's serverless filesystem, and so a KB change shows up as a
 * reviewable diff in the pull request.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const helpDir = join(here, "..", "..", "docs", "help");
const outFile = join(here, "..", "lib", "kb-data.ts");

function parse(raw, file) {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error(`${file}: missing frontmatter`);
  const meta = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^([a-zA-Z_]+):\s*(.*)$/);
    if (!kv) continue;
    meta[kv[1]] = kv[2].trim();
  }
  if (!meta.id || !meta.title) throw new Error(`${file}: id and title are required`);
  const tags = (meta.tags || "")
    .replace(/^\[|\]$/g, "")
    .split(",")
    .map((t) => t.trim())
    .filter(Boolean);
  return { id: meta.id, title: meta.title, tags, body: m[2].trim() };
}

const articles = readdirSync(helpDir)
  .filter((f) => f.endsWith(".md") && f !== "README.md")
  .sort()
  .map((f) => parse(readFileSync(join(helpDir, f), "utf8"), f));

const ids = new Set();
for (const a of articles) {
  if (ids.has(a.id)) throw new Error(`duplicate article id: ${a.id}`);
  ids.add(a.id);
}

writeFileSync(
  outFile,
  `// AUTO-GENERATED by scripts/build-kb.mjs from docs/help/*.md. Do not edit by hand.\n` +
    `import type { Article } from "./kb";\n\n` +
    `export const ARTICLES: Article[] = ${JSON.stringify(articles, null, 2)};\n`,
);

console.log(`build-kb: ${articles.length} articles -> lib/kb-data.ts`);
